clc;
clear;

outputDir = fullfile(pwd, 'cst-output');
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

cst = actxserver('CSTStudio.Application');
mws = invoke(cst, 'NewMWS');

defineUnits(mws, 'mm', 'GHz', 'ns', 'Kelvin');
defineFrequencyRange(mws, 8, 12);
defineBoundaries(mws, 'expanded open', 'expanded open', 'expanded open', 'expanded open', 'electric', 'expanded open');
invoke(mws, 'AddToHistory', 'select time domain solver', 'ChangeSolverType "HF Time Domain"');

addBrick(mws, 'ground', 'component1', 'PEC', [-10, 10], [-10, 10], [0, 0.035]);
addBrick(mws, 'substrate', 'component1', 'Vacuum', [-10, 10], [-10, 10], [0.035, 1.6]);
addPlaneWave(mws, [0, 0, -1], [1, 0, 0]);
addFrequencyMonitor(mws, 'Efield', 10);
addFrequencyMonitor(mws, 'Farfield', 10);

projectFile = fullfile(outputDir, 'basic_plane_wave_project.cst');
invoke(mws, 'SaveAs', projectFile, 'True');
fprintf('CST_PROJECT=%s\n', projectFile);

function defineUnits(mws, geometryUnit, frequencyUnit, timeUnit, temperatureUnit)
s = sprintf(['With Units\n' ...
    '.Geometry "%s"\n' ...
    '.Frequency "%s"\n' ...
    '.Time "%s"\n' ...
    '.TemperatureUnit "%s"\n' ...
    'End With'], geometryUnit, frequencyUnit, timeUnit, temperatureUnit);
invoke(mws, 'AddToHistory', 'define units', s);
end

function defineFrequencyRange(mws, fmin, fmax)
s = sprintf('Solver.FrequencyRange "%g", "%g"', fmin, fmax);
invoke(mws, 'AddToHistory', 'define frequency range', s);
end

function defineBoundaries(mws, xmin, xmax, ymin, ymax, zmin, zmax)
s = sprintf(['With Boundary\n' ...
    '.Xmin "%s"\n' ...
    '.Xmax "%s"\n' ...
    '.Ymin "%s"\n' ...
    '.Ymax "%s"\n' ...
    '.Zmin "%s"\n' ...
    '.Zmax "%s"\n' ...
    'End With'], xmin, xmax, ymin, ymax, zmin, zmax);
invoke(mws, 'AddToHistory', 'define boundaries', s);
end

function addBrick(mws, name, component, material, xrange, yrange, zrange)
s = sprintf(['With Brick\n' ...
    '.Reset\n' ...
    '.Name "%s"\n' ...
    '.Component "%s"\n' ...
    '.Material "%s"\n' ...
    '.Xrange "%g", "%g"\n' ...
    '.Yrange "%g", "%g"\n' ...
    '.Zrange "%g", "%g"\n' ...
    '.Create\n' ...
    'End With'], name, component, material, xrange(1), xrange(2), yrange(1), yrange(2), zrange(1), zrange(2));
invoke(mws, 'AddToHistory', sprintf('define brick: %s:%s', component, name), s);
end

function addPlaneWave(mws, normalVec, eVec)
s = sprintf(['With PlaneWave\n' ...
    '.Reset\n' ...
    '.Normal "%g", "%g", "%g"\n' ...
    '.EVector "%g", "%g", "%g"\n' ...
    '.Store\n' ...
    'End With'], normalVec(1), normalVec(2), normalVec(3), eVec(1), eVec(2), eVec(3));
invoke(mws, 'AddToHistory', 'define plane wave', s);
end

function addFrequencyMonitor(mws, fieldType, freqGHz)
name = sprintf('%s_%gGHz', fieldType, freqGHz);
s = sprintf(['With Monitor\n' ...
    '.Reset\n' ...
    '.Name "%s"\n'], name);
if ~strcmp(fieldType, 'Farfield')
    s = [s sprintf('.Dimension "Volume"\n')];
end
s = [s sprintf(['.Domain "Frequency"\n' ...
    '.FieldType "%s"\n' ...
    '.Frequency "%g"\n' ...
    '.Create\n' ...
    'End With'], fieldType, freqGHz)];
invoke(mws, 'AddToHistory', sprintf('define monitor: %s', name), s);
end
